# Generated by Django 3.0.9 on 2020-08-04 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Strands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('competency_num', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency')),
            ],
        ),
        migrations.CreateModel(
            name='SelfAssessmentAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessee_num', models.IntegerField()),
                ('competency_num', models.IntegerField()),
                ('average', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessee_average', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAssessingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessee_num', models.IntegerField()),
                ('competency_num', models.IntegerField()),
                ('average', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesser_average', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competency_num', models.IntegerField()),
                ('strands_num', models.IntegerField()),
                ('assessing_num', models.IntegerField()),
                ('assessed_num', models.IntegerField()),
                ('value', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency')),
                ('person_assessed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessee', to=settings.AUTH_USER_MODEL)),
                ('person_assessing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesser', to=settings.AUTH_USER_MODEL)),
                ('strands', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Strands')),
            ],
        ),
    ]
