# Generated by Django 3.0.8 on 2020-07-29 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentmodel',
            old_name='manager_num',
            new_name='assessed_num',
        ),
        migrations.RenameField(
            model_name='assessmentmodel',
            old_name='reportee_num',
            new_name='assessing_num',
        ),
        migrations.RemoveField(
            model_name='assessmentmodel',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='assessmentmodel',
            name='reportee',
        ),
        migrations.AddField(
            model_name='assessmentmodel',
            name='person_assessed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assessee', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentmodel',
            name='person_assessing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assesser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
