# Generated by Django 3.0.8 on 2020-07-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_auto_20200729_0950'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodel',
            name='strands_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
