# Generated by Django 3.0.8 on 2020-08-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_assessmentmodel_strands_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodel',
            name='competency',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentmodel',
            name='competency_num',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competency',
            name='average',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
