# Generated by Django 3.0.8 on 2020-08-03 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessment', '0004_auto_20200803_0109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='average',
        ),
        migrations.CreateModel(
            name='SelfAssessmentAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessee_average', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency')),
            ],
        ),
        migrations.CreateModel(
            name='PersonAssessingAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assesser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assesser_average', to=settings.AUTH_USER_MODEL)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency')),
            ],
        ),
    ]
