# Generated by Django 3.0.8 on 2020-08-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0005_auto_20200803_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfassessmentaverage',
            name='assessee_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selfassessmentaverage',
            name='competency_num',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
