# Generated by Django 3.0.8 on 2020-08-03 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auto_20200803_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='personassessingaverage',
            name='assesser_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='personassessingaverage',
            name='competency_num',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
