# Generated by Django 3.0.8 on 2020-08-03 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_auto_20200803_1618'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personassessingaverage',
            old_name='assesser',
            new_name='assessee',
        ),
        migrations.RenameField(
            model_name='personassessingaverage',
            old_name='assesser_num',
            new_name='assessee_num',
        ),
    ]
