# Generated by Django 3.0.8 on 2020-07-25 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
        ('supervisor', '0002_auto_20200725_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('department_name', models.CharField(max_length=50)),
                ('department_code', models.CharField(max_length=50)),
                ('manager_id_num', models.IntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ManagerProfile')),
            ],
        ),
    ]
