# Generated by Django 3.0.9 on 2020-08-05 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationalOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('completed_assessments', models.IntegerField(blank=True)),
                ('num_of_departments', models.IntegerField(blank=True)),
                ('expected_assessments', models.IntegerField(blank=True)),
                ('pending_assessments', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentsRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('percent_progress', models.IntegerField(blank=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisor.Department')),
            ],
        ),
    ]
