# Generated by Django 3.0.9 on 2020-08-05 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
        ('assessment', '0001_initial'),
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalOverview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3)),
                ('completed_assessments', models.IntegerField(blank=True)),
                ('expected_assessments', models.IntegerField(blank=True)),
                ('pending_assessments', models.IntegerField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisor.Department')),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentalCompetencies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('avg_rating', models.IntegerField(blank=True)),
                ('competency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessment.Competency')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supervisor.Department')),
            ],
        ),
    ]
