# Generated by Django 3.0.9 on 2020-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_departmentalcompetencies_departmentaloverview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentalcompetencies',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
