# Generated by Django 3.0.9 on 2020-08-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0003_auto_20200805_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentalcompetencies',
            name='avg_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
